### ISSUE TITLE
Cannot add new column to the table view

### ISSUE THREAD

**Issue by drkovalskyi** [alja/FireworksWeb#79]
Tried to add a column with the following data for Electrons:
`i.genLepton().pdgId()`
No errors. In the log I see:
> MIR,AddNewColumnToCurrentCollection( "i.genLepton().pdgId()", "genLepton" ),45,ROOT::Experimental::REveTableViewInfo

**Comment by alja** [comment]
@drkovalskyi This is a cling problem with the latest root we are using. Some functions are missing. Philip and I are debugging this.

**Comment by alja** [comment]
@drkovalskyi
